config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'my_ads', to: 'dashboard#index', as: 'my_ads'
  get 'banned', to: 'welcome#banned', as: 'banned'
  get 'chat_room', to: 'welcome#chat_user', as: 'chat_room'

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users do
    resources :profiles, only: %i[edit update show]
    resources :user_reviews
  end

  resources :chat_rooms, only: [:create] do
    member do
      post :close
    end
    resources :latters, only: [:create]
  end

  resources :ads do
    get :favourite, on: :member
  end

  resources :categories do
    resources :ads
  end

  root 'welcome#index'

  namespace :admin do
    root 'users#index'
    resources :users do
      get :change_permission, on: :member
      get :ad_to_black_list, on: :member
    end
    resources :ads do
      get :ad_approval, on: :member
    end
    resources :categories
  end
end

app/views/shared/_footer.html.slim
link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" 
  footer.footer1
    .container
      .row
        /! row
        .col-lg-4.col-md-4.col-xs-6
          /! widgets column left
          ul.list-unstyled.clear-margins
            /! widgets
            li.widget-container.widget_nav_menu
              /! widgets list
              h1.title-widget Useful links
              ul
                li= link_to root_path do
                  i.fa.fa-angle-double-right
                  | Home page
                li= link_to ads_path do
                  i.fa.fa-angle-double-right
                  | Ads
                li= link_to contact_path do
                  i.fa.fa-angle-double-right
                  | Contact Us
        .col-lg-4.col-md-4.col-xs-6
        .col-lg-4.col-md-4.col-xs-6
          ul.list-unstyled.clear-margins
            li.widget-container.widget_recent_news
              h1.title-widget Contact Detail
              .footerp
                p
                  b Email id:
                  a href="mailto:gtafan51@gmail.com"  gtafan51@gmail.com
                p
                  b Helpline Numbers
                  b style="color:#ffc106;"  (8AM to 10PM):
                  p 88005553535
              .social-icons
                ul.nomargin
                  a href="https://www.facebook.com/bootsnipp" 
                    i#social.fa.fa-facebook-square.fa-3x.social-fb
                  a href="https://twitter.com/bootsnipp" 
                    i#social.fa.fa-twitter-square.fa-3x.social-tw
                  a href="https://plus.google.com/+Bootsnipp-page" 
                    i#social.fa.fa-google-plus-square.fa-3x.social-gp
                  a href="mailto:bootsnipp@gmail.com" 
                    i#social.fa.fa-envelope-square.fa-3x.social-em
  .footer-bottom
    .container
      .row
        .col-xs-12.col-sm-6.col-md-6.col-lg-6
          .copyright
            | &#xA9; 2017, CrashGtaFan, All rights reserved

app/views/shared/_header.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded='false' data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button' 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a
        = link_to root_path, class: 'navbar-brand' do
          = fa_icon 'usd'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-left
        li= link_to 'Ads', ads_path
        li= link_to 'Contacts', contact_path
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li.dropdown
            a.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown' href='#' role='button'
              = current_user.name_space
              = image_tag current_user.profile.avatar_url(:small), class: 'avatar_header_style img-circle'
              span.caret
            ul.dropdown-menu
              li= link_to 'My Profile', user_profile_path(current_user, current_user.profile)
              li= link_to 'My ads', my_ads_path
              li= link_to 'Messages', chat_room_path
              - if current_user.try(:admin)
                li= link_to 'Admin panel', admin_root_path
              li.divider role='separator' 
              li= link_to 'Log Out', destroy_user_session_path, method: :delete
        - if current_user
          li= link_to 'Log Out', destroy_user_session_path, method: :delete
        - else
          li= link_to 'Sign Up', new_user_registration_path
          li= link_to 'Login', new_user_session_path