config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'my_ads', to: 'dashboard#index', as: 'my_ads'
  get 'banned', to: 'welcome#banned', as: 'banned'
  get 'chat_room', to: 'welcome#chat_user', as: 'chat_room'

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users do
    resources :profiles, only: %i[edit update show]
    resources :user_reviews
  end

  resources :chat_rooms, only: [:create] do
    member do
      post :close
    end
    resources :latters, only: [:create]
  end

  resources :ads do
    get :favourite, on: :member
  end

  resources :categories do
    resources :ads
  end

  root 'welcome#index'

  namespace :admin do
    root 'users#index'
    resources :users do
      get :change_permission, on: :member
      get :ad_to_black_list, on: :member
    end
    resources :ads do
      get :ad_approval, on: :member
    end
    resources :categories
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @categories = Category.without_parent
    @ads = Ad.published.latest.limit(6)
    @users = User.latest_by_ads.limit(5)
  end

  def chat_user
    session[:chat_rooms] ||= []
 
    @users = User.all.where.not(id: current_user)
    @chat_rooms = ChatRoom.includes(:recipient, :latters)
                                 .find(session[:chat_rooms])
  end
end

app/views/welcome/banned.html.slim
.row
  .col-md-6.col-xs-12.col-md-offset-3
    center
      h2 You are added to the black-list of our site!
      p= image_tag src='/assets/stop.png', class: 'stop-image'
      h3= link_to 'Redirect to main page', root_path

app/views/welcome/chat_user.html.slim
.row
  .col-md-9
    ul#chat_rooms-list
      - @chat_rooms.each do |chat_room|
        = render 'chat_rooms/chat_room', chat_room: chat_room, user: current_user
  .col-md-3
    .panel.panel-primary
      .panel-heading
        h3.panel-title User list
      .panel-body
        ul
          - @users.each do |user|
            li
              = image_tag user.profile.avatar_url(:small), class: 'avatar_header_style img-circle'
              = link_to user.name_space, chat_rooms_path(user_id: user), remote: true, method: :post
              br

app/views/welcome/index.html.slim
.row
  .col-md-8.col-xs-12
    .jumbotron
      h2 Welcome to the site for placing ads
      p If this is your first visit, you can register. If you have an account, then you can login
      - unless current_user
        .btn.btn-group
          = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-info btn-sm'
          = link_to 'Login', new_user_session_path, class: 'btn btn-primary btn-sm'
  .col-md-4.col-xs-12
    = cl_image_tag('w128h1281371488121classifieds128_ahnzmj.png', width: 160, crop: 'scale')
    - unless @users.count.blank?
      p.title_ads Active users:
      table.table.table-hover
        - @users.each do |user|
          tr.success
            td= user.name_space
            td= pluralize user.ads.published.length, 'Ad'
h1
  center Latest Ads
.row
  .col-md-10.col-md-offset-1
    - @ads.each do |ad|
      .col-md-4.col-xs-12.col-sm-6.well.new_ads_block
        center
          = link_to ad_path(ad) do
            = image_tag ad.image_ad_url(:thumb), class: 'thumbnail ads_index'
        = cl_image_tag('new_hb6wbj.png', width: 50, crop: 'scale')
        = link_to ad.name, ad_path(ad)
        h4= number_to_currency(ad.price)
        p
          b #{time_ago_in_words(ad.created_at)} ago
        p