config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'my_ads', to: 'dashboard#index', as: 'my_ads'
  get 'banned', to: 'welcome#banned', as: 'banned'
  get 'chat_room', to: 'welcome#chat_user', as: 'chat_room'

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users do
    resources :profiles, only: %i[edit update show]
    resources :user_reviews
  end

  resources :chat_rooms, only: [:create] do
    member do
      post :close
    end
    resources :latters, only: [:create]
  end

  resources :ads do
    get :favourite, on: :member
  end

  resources :categories do
    resources :ads
  end

  root 'welcome#index'

  namespace :admin do
    root 'users#index'
    resources :users do
      get :change_permission, on: :member
      get :ad_to_black_list, on: :member
    end
    resources :ads do
      get :ad_approval, on: :member
    end
    resources :categories
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :subcategories, class_name: 'Category',
                           foreign_key: :parent_category_id,
                           dependent: :destroy

  has_and_belongs_to_many :ads, dependent: :delete_all

  has_one :parent, class_name: 'Category',
                   primary_key: :parent_category_id, foreign_key: :id

  accepts_nested_attributes_for :subcategories, allow_destroy: true

  scope :without_parent, -> { where(parent_category_id: nil) }
  scope :without_subcategory, -> { where('parent_category_id IS NOT NULL') }
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < AdminsController
  before_action :category_resource, only: [:destroy]

  def new
    @category = Category.new
    @category.subcategories.build
  end

  def index
    @categories = Category.includes(:subcategories)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    @category.destroy!
  end

  private

  def category_params
    params.require(:category).permit(:name, subcategories_attributes: %i[name parent_category_id _destroy])
  end

  def category_resource
    @category = Category.find(params[:id])
  end
end

app/views/admin/categories/_form.html.slim
.col-xs-12.col-md-8.col-md-offset-2
  = form_for [:admin, @category], remote: true do |f|
    = f.label :name
    br
    = f.text_field :name, placeholder: :name, class: 'form-control'
    br
    .well
      h3
        center Subcategories
      br
      = f.nested_fields_for :subcategories do |ff|
        .col-xs-9.col-md-9
          = ff.text_field :name, placeholder: 'Enter name subcategory', class: 'form-control'
          = ff.hidden_field :parent_category_id, value: @category.id
          br
        .col-xs-3.col-md-3
          = ff.remove_nested_fields_link 'Remove', class: 'btn btn-danger'
      br
      center= f.add_nested_fields_link :subcategories, 'Add more', class: 'btn btn-success'
      br
    = f.submit class: 'btn btn-success'

app/views/admin/categories/_subcategory.html.slim
- subcategories.each do |sub|
  tr id='subcategories_#{subcategories.name}'
    td.child_category_name
      = sub.name
    td

app/views/admin/categories/index.html.slim
h1 Categories
.button
  = link_to 'New Category', new_admin_category_path, id: 'new_category', remote: true, class: 'btn btn-primary'
.col-md-8.col-xs-12.col-md-offset-2
  table.table.table-hover
    thead
      tr
        th Name
        th Action
    tbody
      .all_categories
        - @categories.each do |category|
          - if category.parent_category_id.blank?
            tr id='category_#{category.id}'
              td= category.name
              td= link_to 'Delete category', admin_category_path(category), method: :delete, remote: true, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-xs'
          = render partial: 'subcategory', locals: {subcategories: category.subcategories} if category.subcategories.present?

app/views/admin/categories/new.html.slim
h1
  center New category
= render 'form'