config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'my_ads', to: 'dashboard#index', as: 'my_ads'
  get 'banned', to: 'welcome#banned', as: 'banned'
  get 'chat_room', to: 'welcome#chat_user', as: 'chat_room'

  get 'contact', to: 'messages#new', as: 'contact'
  post 'contact', to: 'messages#create'

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users do
    resources :profiles, only: %i[edit update show]
    resources :user_reviews
  end

  resources :chat_rooms, only: [:create] do
    member do
      post :close
    end
    resources :latters, only: [:create]
  end

  resources :ads do
    get :favourite, on: :member
  end

  resources :categories do
    resources :ads
  end

  root 'welcome#index'

  namespace :admin do
    root 'users#index'
    resources :users do
      get :change_permission, on: :member
      get :ad_to_black_list, on: :member
    end
    resources :ads do
      get :ad_approval, on: :member
    end
    resources :categories
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,  :omniauthable, :omniauth_providers => [:facebook]

  has_many :categories
  has_many :ads, dependent: :destroy
  has_many :ads_views, dependent: :destroy
  has_many :favourite_ads, dependent: :destroy
  has_many :user_reviews, dependent: :destroy

  has_many :latters, dependent: :destroy
  has_many :chat_rooms, foreign_key: :sender_id

  has_one :profile, dependent: :destroy

  scope :latest_by_ads, -> { order(ads_count: :desc) }

  before_create :build_profile

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      binding.pry
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.profile.first_name = auth.info.name.split(' ').first
      # user.profile.last_name = auth.info.name.split(' ').second
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def name_space
    if profile.full_name.delete(' ').length.zero?
      email
    else
      profile.full_name
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < AdminsController
  before_action :user_resource, only: %i[destroy change_permission ad_to_black_list]

  def index
    @users = User.order(:id)
    @banned_users = User.where(banned: true)
  end

  def destroy
    @user.destroy!
  end

  def change_permission
    @user.update(admin: !@user.admin)
    redirect_to :back
  end

  def ad_to_black_list
    @user.update(banned: !@user.banned)
    redirect_to :back
  end

  private

  def user_resource
    @user = User.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/views/admin/users/_ban_list.html.slim
.title_ads Black-list
table.table.table-striped
  thead
    tr.danger
      th #
      th Full name
      th Username
      th Avatar
      th Birthday
      th Email
      th Phone
      th
  tbody
    - @banned_users.each do |user|
      tr id='user_#{user.id}'
        td= user.id
        td= user.profile.full_name
        td= user.profile.username
        td= image_tag user.profile.avatar_url(:small), class: 'avatar_header img-circle'
        td= user.profile.birthday
        td= user.email
        td= user.profile.phone
		- if user.banned
          td= link_to 'Remove to ban-list', ad_to_black_list_admin_user_path(user),  class: 'btn btn-warning btn-sm'

app/views/admin/users/_thead_user.html.slim
tr
  th #
  th Full name
  th Username
  th Avatar
  th Birthday
  th Email
  th Phone
  th Role
  th

app/views/admin/users/_users.html.slim
.title_ads Users list
- @users.each do |user|
  tr id='user_#{user.id}' class="#{user.banned ? 'danger' : 'default'}"
    td= user.id
    td= user.profile.full_name
    td= user.profile.username
    td= image_tag user.profile.avatar_url(:small), class: 'avatar_header img-circle'
    td= user.profile.birthday
    td= user.email
    td= user.profile.phone
    - if user.admin?
      td Admin
    - else
      td User
    td
      .btn-group
        button.btn.btn-info.btn-sm.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown' type='button'
          | Action
          span.caret
        ul.dropdown-menu
          - if user.admin
            li= link_to 'Assign user', change_permission_admin_user_path(user)
          - else
            li= link_to 'Assign admin', change_permission_admin_user_path(user)
          - unless user.banned
            li= link_to 'Ad to ban-list', ad_to_black_list_admin_user_path(user)
          li.divider role='separator'
          li= link_to 'Delete user', admin_user_path(user), method: :delete, remote: true, data: { confirm: 'Are you sure?'}

app/views/admin/users/index.html.slim
h1 All users
.row
  .col-md-12.col-xs-12.col-sm-10
    ul.nav.nav-pills.nav-justified
      li.active role="presentation" 
        a href="#tab-1" data-toggle="tab" Users list
      li role="presentation" 
        a href="#tab-2" data-toggle="tab" Black-list
.row
  .col-md-12.col-xs-12.col-sm-10
    .tab-content
      #tab-1.tab-pane.fade.in.active
        table.table.table-hover
          thead
            = render 'thead_user'
          tbody
            = render 'users'
      #tab-2.tab-pane.fade
        - unless @banned_users.empty?
          = render 'ban_list'
        - else
          center
            h1.text-primary The black-list a empty